### ISSUE TITLE
[FEATURE REQUEST] Add photo library management

### ISSUE THREAD

**Issue by lsouchet** [scholtzm/arnold#51]
Hello,
First of all, good job for your work, it looks pretty nice!
One thing I miss and I haven't been able to find so far is a web interface to manage my kodi photo library.
My pictures are on a NAS and accessed by Kodi, I would love to be able to manage my photo library from a web browser when I am at home.
I have been looking at [Lychee](https://github.com/electerious/Lychee) which seems to fit my needs and is open source.
I don't know how hard it would be to link it to Kodi library.
Anyway I would love something making my able to browse through my picture library and create albums.

**Comment by scholtzm** [comment]
Have you tried Chorus2? It's the default web interface in Kodi v17.

https://github.com/xbmc/chorus2

I'm not sure I'm going to work on Arnold any more. If anything, I'll most likely contribute to Chorus2.

**Comment by lsouchet** [comment]
Correct me if I'm wrong, but I don't think Chorus2 handles picture libraries either.
Do you suggest me to open a Feature request to Chorus2?

**Comment by scholtzm** [comment]
I haven't used Chorus2 very extensively myself but if it doesn't handle image libraries then indeed I'd suggest opening a feature request. It has bigger community and in the end more people will benefit from the added feature. 👍

**Comment by lsouchet** [comment]
[Alright](https://github.com/xbmc/chorus2/issues/246) 
Thank you for your quick answer!
